let
    Source = Excel.Workbook(File.Contents(Path & "WW SSP Tools and Processes - SSP Data Library\Data Modules\LVL2_RAW_Data\LVL2_Volume_PN.xlsx"), null, true),
    export_FY21FY22_Table = Source{[Item="export_FY21FY22",Kind="Table"]}[Data],
    #"Appended Query" = Table.Combine({export_FY21FY22_Table, export_FY17FY18, export_FY19FY20}),
    #"Changed Type" = Table.TransformColumnTypes(#"Appended Query",{{"Fiscal Year", type text}, {"Qtr", type text}, {"Funded date", type date}, {"Partner - Focus", type text}, {"GM(%)", type number}, {"Bus unit group", type text}, {"Month", type date}, {"GEO", type text}, {"Country", type text}, {"Entity", type text}, {"HPFS segment", type text}, {"Customer ID", type text}, {"Customer name", type text}, {"Partner - Locator ID", type text}, {"Partner group", type text}, {"ST Top Number", type text}, {"ST Number", type text}, {"CD segment", type text}, {"Distributor ID", Int64.Type}, {"Industry", type text}, {"Customer DUNS no.", type text}, {"MDCP ID_org", type text}, {"Vertical", type text}, {"ST Name", type text}, {"FAM name", type text}, {"Partner subgroup", type text}, {"Channel exceptions", type any}, {"Lease start", type date}, {"Sales Supervisor", type text}, {"Product number", type text}, {"GL", type text}, {"Sales Manager", type text}, {"Project name", type text}, {"Region Manager", type text}, {"Maturity date", type date}, {"Party ID", Int64.Type}, {"Party ID - end user", Int64.Type}, {"MDCP ID (SLED)", type text}, {"Business group", type text}, {"HPE/I product", type text}, {"MDCP name (SLED)", type text}, {"Product line desc.", type text}, {"Quantity", Int64.Type}, {"Schedule", type text}, {"Bus unit sub-group", type text}, {"Contract admin", type text}, {"Frequency (#)", Int64.Type}, {"Term", Int64.Type}, {"Sales motion", type text}, {"Adv Arr", type text}, {"Services/Direct type", type text}, {"Bus unit desc", type text}, {"Bus unit class", type text}, {"Sched promo", type text}, {"Compliancy", type text}, {"Lease class", type text}, {"Partner type", type text}, {"Partner - HPI ID", type text}, {"Lease model", type text}, {"Product category desc.", type text}, {"RV% (pricing)", type number}, {"PL", type text}, {"Partner - Strategic", type text}, {"Sublease (APJ)", type any}, {"Sublease ID (APJ)", type any}, {"HW / SW", type text}, {"Manufacturer", type text}, {"Purch. opt. method", type text}, {"Product name", type text}, {"HPE coverage code", type text}, {"HP Non-HP", type text}, {"Services (Y/N)", type text}, {"GreenLake type", type any}, {"Sub Seg", type text}, {"Reseller ID", type text}, {"Product type", type text}, {"Partner country", type text}, {"Reseller name", type text}, {"Bus Sub Segment", type text}, {"Dir / Indir", type text}, {"Subregion", type text}, {"Partner - HPE ID", type text}, {"Partner connect", type text}, {"Business segment", type text}, {"PC business mode", type text}, {"Distributor name", type text}, {"Partner - HPEFS level", type text}, {"Partner - Ownership", type text}, {"Thru channel flag", type text}, {"SMB metrics", type text}, {"Frequency", type text}, {"Risk rating", Int64.Type}, {"Currency (Deal)", type text}, {"Currency (Inv)", type text}, {"Portfolio ID", type text}, {"Deal source", type text}, {"Billing method", type text}, {"APA?", type text}, {"Partner state", type any}, {"Customer state", type text}, {"Partner - HPI level", type text}, {"Partner - HPE level", type text}, {"Partner - HPE focus", type text}, {"FMV", type text}, {"DXC Cluster", type text}, {"DXC Country", type text}, {"PS Type", type text}, {"A3/A4 attach", type text}, {"Target ROE", type number}, {"SLB", type text}, {"Actual ROE", type number}, {"Partner - 3D", type text}, {"Partner - A3", type text}, {"IRR with RV (see note)", type any}, {"COF", type number}, {"Partner - Nimble", type text}, {"HPE - sub-region", type text}, {"HPE - region", type text}, {"HPI - region", type text}, {"Partner - FMV", type text}, {"Unique customer ST", type text}, {"HPI Tier", type text}, {"ECP Overlay", type any}, {"PDM Partner name", type any}, {"ECP Distributor name", type any}, {"Ref. Partner ID", Int64.Type}, {"Ref. Partner name", type text}, {"Comp Eligible", type text}, {"Partner - Aruba", type text}, {"Partner - CA license", type text}, {"Partner - PointNext", type text}, {"Partner - Print", type text}, {"Accounting rate", type number}, {"DRA account", type text}, {"Overlay name", type text}, {"PDM name", type text}, {"AR territory", type any}, {"iMPS", type text}, {"dMPS", type any}, {"Sales role", type text}, {"Distributor flag", type text}, {"WBS", type any}, {"PDM overlay", type any}, {"PPT flag", type text}, {"Party name - end user", type text}, {"Max UPM payments", type text}, {"FAM ID", Int64.Type}, {"Lease term (grouped)", Int64.Type}, {"Sales E2E team", type text}, {"Yield", type number}, {"LRF", type number}, {"Volume in USD (Sum)", type number}, {"GM($)", type number}, {"GBU Description", type text}, {"HP Company", type text}, {"HPI MPS GBU PL", type any}, {"HPE/HPI/NON-HP", type text}, {"WW Sales Territory Name", type text}, {"WW top sales territory name", type text}, {"End User name", type text}, {"DaaS", type text}, {"MPS exclude flag", type text}, {"MPS", type text}, {"PN", type text}, {"Aruba", type text}, {"HPI MPS Flag", type text}, {"Country group", type text}, {"Region", type text}, {"Subregion(country based)", type text}, {"Distributor?", type text}, {"Term Buckets", type text}, {"$ FMV", Int64.Type}, {"$ PC", Int64.Type}, {"$ Disti", Int64.Type}, {"$ COF", type number}, {"$ Yield", type number}, {"$ Target ROE", type number}, {"$ Actual ROE", type number}, {"Fiscal Year - Copy", Int64.Type}, {"Qtr - Copy", type text}, {"MDCP ID", type text}, {"Mth buckets", Int64.Type}, {"PDM Flag", type text}, {"PDM/ECP Partner Name", type text}, {"VM($)", type number}}),
    #"Merged Queries3" = Table.NestedJoin(#"Changed Type", {"PL"}, LVL0_Product_PL, {"HP PL"}, "LVL0_Product_PL", JoinKind.LeftOuter),
    #"Expanded LVL0_Product_PL" = Table.ExpandTableColumn(#"Merged Queries3", "LVL0_Product_PL", {"Addressable", "Addressable %", "China PLs to be excl"}, {"LVL0_Product_PL.Addressable", "LVL0_Product_PL.Addressable %", "LVL0_Product_PL.China PLs to be excl"}),
    #"Added Custom1" = Table.AddColumn(#"Expanded LVL0_Product_PL", "$ addresable Vol", each [#"Volume in USD (Sum)"]*([#"LVL0_Product_PL.Addressable %"]/100)),
    #"Added Custom3" = Table.AddColumn(#"Added Custom1", "china excl", each if[LVL0_Product_PL.China PLs to be excl]="Y" and [Country]="CHINA" then "Y" else "N"),
    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom3",{{"$ addresable Vol", type number}, {"dMPS", type text}}),
    #"Renamed Columns" = Table.RenameColumns(#"Changed Type1",{{"MDCP ID", "MDCP ID_old"}, {"ST Top Number", "ST Top Number_2"}}),
    #"Added Custom4" = Table.AddColumn(#"Renamed Columns", "ST Top Number", each if [Sales E2E team] = "GLB DXC" then "511267429" else [ST Top Number_2]),
    #"Replaced Value" = Table.ReplaceValue(#"Added Custom4","","no sled id",Replacer.ReplaceValue,{"MDCP ID (SLED)"}),
    #"Added Custom" = Table.AddColumn(#"Replaced Value", "MDCP ID", each if[#"MDCP ID (SLED)"]<>"no sled id" then [#"MDCP ID (SLED)"]else [MDCP ID_old]),
    #"Added Custom2" = Table.AddColumn(#"Added Custom", "Focus areas", each if[Business group]="Personal Systems" and Text.Contains([Lease model],"HPI INTEGRATED LEASE") then "DaaS" else if[Business group]="Personal Systems" and [MPS]="N" then "PS Direct Financing" else if[iMPS]="iMPS" then "iMPS" else if [dMPS]="dMPS" then "dMPS" else if Text.Contains([GBU desc],"3D") then "3D" else if Text.Contains([GBU desc],"GSB") then "GSB" else "Other HPI"),
    #"Uppercased Text1" = Table.TransformColumns(#"Added Custom2",{{"PDM name", Text.Upper, type text}, {"PDM overlay", Text.Upper, type text}, {"ECP Overlay", Text.Upper, type text}, {"Schedule", Text.Upper, type text}}),
    #"Merged Queries" = Table.NestedJoin(#"Uppercased Text1",{"Country"},LVL0_countries,{"Country (QV)"},"LVL0_countries",JoinKind.LeftOuter),
    #"Expanded LVL0_countries" = Table.ExpandTableColumn(#"Merged Queries", "LVL0_countries", {"SubGEO"}, {"SubGEO"}),
    #"Merged Queries1" = Table.NestedJoin(#"Expanded LVL0_countries",{"ST Top Number", "SubGEO", "Country"},LVL1_Entity_GA_detailed_list,{"Top Parent ST ID", "SubGEO", "Country"},"LVL1_Entity_GA_detailed_list",JoinKind.LeftOuter),
    #"Expanded LVL1_Entity_GA_detailed_list" = Table.ExpandTableColumn(#"Merged Queries1", "LVL1_Entity_GA_detailed_list", {"FY20 PRIMARY FAM"}, {"FY20 PRIMARY FAM"}),
    #"Merged Queries2" = Table.NestedJoin(#"Expanded LVL1_Entity_GA_detailed_list",{"ST Number"},LVL1_Entity_AMS_assignements,{"FY20  Territory ID"},"LVL1_Entity_AMS_assignements",JoinKind.LeftOuter),
    #"Expanded LVL1_Entity_AMS_assignements" = Table.ExpandTableColumn(#"Merged Queries2", "LVL1_Entity_AMS_assignements", {"FY20 FAM"}, {"FY20 FAM"}),
    #"Renamed Columns2" = Table.RenameColumns(#"Expanded LVL1_Entity_AMS_assignements",{{"FY20 PRIMARY FAM", "FY20 GA FAM"}, {"FY20 FAM", "FY20 AMS FAM"}}),
    #"Merged Queries4" = Table.NestedJoin(#"Renamed Columns2",{"Fiscal Year"},#"LVL0_Date_current FY",{"FY_shorter"},"LVL0_Date_current FY",JoinKind.LeftOuter),
    #"Expanded LVL0_Date_current FY" = Table.ExpandTableColumn(#"Merged Queries4", "LVL0_Date_current FY", {"Q_M"}, {"Q_M"}),
    #"Duplicated Column" = Table.DuplicateColumn(#"Expanded LVL0_Date_current FY", "Month", "Month - Copy"),
    #"Changed Type2" = Table.TransformColumnTypes(#"Duplicated Column",{{"Month - Copy", type text}}),
    #"Added Custom9" = Table.AddColumn(#"Changed Type2", "HPEFS enh segment", each if[#"Bus unit sub-group"]="Graphics Solutions" or [Partner type]="GSB" then "GSB" else if [Partner type]="INDIRECT" and [HPFS segment]="SMB" then "SMB TC" else if [HPFS segment]="SMB" then "SMB Other" else if [Partner type]="INDIRECT" and [HPFS segment]="ENTERPRISE" then "ENT TC" else if [HPFS segment]="ENTERPRISE" then "ENT Other" else if [HPFS segment]="GLOBAL" then "GLOBAL" else [HPFS segment]),
    #"Added Custom5" = Table.AddColumn(#"Added Custom9", "MMM", each Date.Month([Month])),
    #"Added Custom6" = Table.AddColumn(#"Added Custom5", "YYYY", each Date.Year([Month])),
    #"Changed Type4" = Table.TransformColumnTypes(#"Added Custom6",{{"MMM", type text}, {"YYYY", type text}}),
    #"Added Custom7" = Table.AddColumn(#"Changed Type4", "key_CRP", each [Schedule] & "-" & [Reseller ID] & "-" & [MMM] & "-" & [YYYY]),
    #"Changed Type3" = Table.TransformColumnTypes(#"Added Custom7",{{"key_CRP", type text}}),
    #"Merged Queries5" = Table.NestedJoin(#"Changed Type3", {"key_CRP"}, LVL2_CRP_vol, {"key_crp"}, "LVL2_CRP_vol", JoinKind.LeftOuter),
    #"Expanded LVL2_CRP_vol" = Table.ExpandTableColumn(#"Merged Queries5", "LVL2_CRP_vol", {"CRP flag", "PC Usage flag", "CAF flag"}, {"CRP flag", "PC Usage flag", "CAF flag"}),
    #"Replaced Value1" = Table.ReplaceValue(#"Expanded LVL2_CRP_vol",null,"N",Replacer.ReplaceValue,{"CRP flag", "PC Usage flag", "CAF flag"}),
    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value1","N","NON CRP",Replacer.ReplaceText,{"CRP flag"}),
    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value3","Y","CRP",Replacer.ReplaceText,{"CRP flag"}),
    #"Renamed Columns1" = Table.RenameColumns(#"Replaced Value2",{{"HPFS segment", "HPFS segment_"}}),
    #"Added Custom8" = Table.AddColumn(#"Renamed Columns1", "HPFS segment", each if[Sales E2E team]="GLB DXC" then "GLOBAL" else [HPFS segment_]),
    #"Added Custom10" = Table.AddColumn(#"Added Custom8", "Term group", each if [Term]<=23 then "1m to 23m" else 
if [Term]=24 then "24m" else
if [Term]<=35 then "25m to 35m" else
if [Term]=36 then "36m" else
if [Term]<=47 then "37m to 47m" else
if [Term]=48 then "48m" else
if [Term]<=59 then "49m to 59m" else
if [Term]=60 then "60m" else
if [Term]<=71 then "61m to 71m" else
if [Term]=72 then "72m" else
"+72m"),
    #"Changed Type5" = Table.TransformColumnTypes(#"Added Custom10",{{"HPFS segment", type text}, {"Term group", type text}})
in
    #"Changed Type5"
